### ISSUE TITLE
Can't create Tea Cup (1.14.3)

### ISSUE THREAD

**Issue by DarkKnightComes** [elucent/SimplyTea#10]
I can't create Tea Cup,but I can create other things (Teapot, Tea Bag) and Tea trees show up. How am I supposed to drink my tea?

![Bez tytułu](https://user-images.githubusercontent.com/16616869/60470062-47af2e80-9c5f-11e9-9b6f-426714221fe7.png)

**Comment by KnightMiner** [comment]
In 1.14 tea cups use white dye instead of bone meal due to Mojang separating the two.

**Comment by DarkKnightComes** [comment]
it's weird that it's not mentioned anywhere, thanks a lot :)
