### ISSUE TITLE
1.14.4: Filling Teapot with milk from a cow causes Teapot to dissapear from inventory.

### ISSUE THREAD

**Issue by RealRossGeller** [elucent/SimplyTea#13]

**Comment by BreadForest** [comment]
I have found the same issue. I can add however that this is only the case when the teapot is not within a stack. Or well, at least in my case.

**Comment by KnightMiner** [comment]
This is probably that annoying inventory bug where it tries to clear the stack from the inventory because the one you replaced is empty. I remember fixing this in 1.12, so I'll have to look into it again

**Comment by KnightMiner** [comment]
Leaving this open as the fix is not yet released.

**Comment by KnightMiner** [comment]
Fixed in 2.0.4
