### ISSUE TITLE
Wood, leaves and fence don't burn

### ISSUE THREAD

**Issue by AragonChristopherR17Z** [elucent/SimplyTea#16]
When put near a flame, none of the wood, leaf or fence blocks burn.

**Comment by KnightMiner** [comment]
Versions?

**Comment by AragonChristopherR17Z** [comment]
> Versions?

Version 2.0.3 on Minecraft 1.14.4 with Forge 28.1.0

**Comment by KnightMiner** [comment]
Fixed in 2.0.4
