### ISSUE TITLE
[1.15.2] Crash on Startup

### ISSUE THREAD

**Issue by Kamefrede** [elucent/SimplyTea#23]
Mod Version: 2.1.0
Forge Version: 31.1.18

Relevant piece of log: https://pastebin.com/mm605GBB

**Comment by KnightMiner** [comment]
Yeah, the mod does not currently support 1.15.2, apparently Forge made breaking changes. I have been too busy to put much time into modding for awhile.

**Comment by i-o-u** [comment]
Is there anything I can do while I wait for a fix?

**Comment by KnightMiner** [comment]
This was fixed by #24
