### ISSUE TITLE
[1.15.2] Tea Trees spawning in The Midnight dimension (2.2.1)

### ISSUE THREAD

**Issue by sirgfsa** [elucent/SimplyTea#27]
Minecraft: 1.15.2
Forge Version: 31.2.0
Mods Used: simplytea-1.15.2-2.2.1.jar, themidnight-0.5.9.jar

![2020-06-06_11 54 21](https://user-images.githubusercontent.com/66380400/83935491-9577d380-a7ec-11ea-8a44-9cdbd5eee299.png)

**Comment by KnightMiner** [comment]
Please cross post this to their Github/other issue tracker and link it here. I'm not entirely convinced its a bad thing.

I currently add the tree to all valid forest biomes, I am not sure if there is a good way to block other dimensions without losing compatibility with biome mods.

**Comment by KnightMiner** [comment]
I am going to go ahead and close this given tea trees as of 1.20 are now handled by biome tags which allow full control over this issue. If you want to stop them from spawning in other dimensions, switch the biome modifier to a overworld specific tag via a datapack.
