### ISSUE TITLE
Teapot consumes source block when its not supposed to, plus if its a waterloged block it destroyes the block.

### ISSUE THREAD

**Issue by AnthropamorphicPersonification** [elucent/SimplyTea#29]
Im using simply tea 1.15.2-2.2.1 and when i fill a teapot with water it uses the source block even though i have the config set to not use the source, and it destroys any waterloged blocks when filling it. I tried setting the config to false in case the description was wrong, but it didn't change anything.

**Comment by KnightMiner** [comment]
Cannot confirm the config issue, but fixed the issue with consuming waterloggable blocks in the next build.

**Comment by KnightMiner** [comment]
Fixed in 2.3.2
