### ISSUE TITLE
[Cross-mod compatibility feature] Refilling teapot with water using sink from Cooking for Blockheads

### ISSUE THREAD

**Issue by AbacusOperator** [elucent/SimplyTea#38]
**Describe your feature here**
Please add ability filling teapot with water using sink from Cooking for Blockheads (cookingforblockheads:sink). Sink is an infinite water source block, from which water can be extract with bucket, bottle or pumping.

**Comment by dkmk100** [comment]
Also the cow in a bucket for milk

**Comment by KnightMiner** [comment]
Going to close this in favor of #46, which is the same idea but more general
