### ISSUE TITLE
Add Forge tags to items

### ISSUE THREAD

**Issue by TheDarkPreacher** [elucent/SimplyTea#39]
Just a suggestion to add in some compatibility between mods, adding the Forge tags to items or recipes so things like Thermal's tea can be used as an alternative item.

(this also opens the possibility of adding a coffee item that can be present when Thermal is in the pack, possibly with a flavor text of "It'll do, I suppose." or something similar.)

**Comment by KnightMiner** [comment]
Add tags for what? Thermal is like, 6 mods, do they add tea leaves in one now?

**Comment by TheDarkPreacher** [comment]
Thermal Cultivation has added crops, but it hardly has any actual foods associated with it. Mostly you can make "crates" which are just decorative storage blocks. And you can eat the crop drops as well. There are tea leaves and coffee in those crops.

**Comment by KnightMiner** [comment]
Added tea leaves to a tag in 2.4.0, did not see any other tags worth adding.
