### ISSUE TITLE
Add config to disable ice drops

### ISSUE THREAD

**Issue by Sagragoth** [elucent/SimplyTea#42]
Currently both Neapolitan and SimplyTea add ice cubes that drop when breaking ice.  It would be nice to be able to disable ice dropping and use one or the other in the config. [Enhancement]

**Comment by KnightMiner** [comment]
You can disable ice cube drops with a datapack pretty easily. Its just a global loot modifier JSON

**Comment by BodhiSmith13** [comment]
I managed to disable ice cube drops by removing them from simply tea's global loot modifiers using a datapack. This seemed a bit too easy though.

**Comment by KnightMiner** [comment]
Too easy? Datapacks are easy.

**Comment by BodhiSmith13** [comment]
I meant that I'm worried that it might have some sort of negative side effect. I'm new to modpack making and datapacks, so I'm not exactly certain of the consequences of my actions. Do you think they'll have any unintended outcomes?

**Comment by KnightMiner** [comment]
That file just adds the drop. The whole reason its JSON is so you can disabled it. If you disabled it via the ice drops JSON itself, that will work as long as you get no log errors.

If you disabled it using the forge list of global loot modifiers, make sure you did not acidently remove any other mods' modifiers. Mantle can print you a list of all active modifiers under its `/mantle` command, it works pretty much like tags (replace overrides all previous)

**Comment by KnightMiner** [comment]
Closing as this can be disabled via loot tables/global loot modifers
