### ISSUE TITLE
Suggestion:  rename 'Tea cup' to Cup

### ISSUE THREAD

**Issue by HopsandBarley** [elucent/SimplyTea#43]
Just a suggestion to rename the 'Tea Cup' and 'Unfired Tea Cup' to 'Cup' and 'Unfired Cup' .  This will allow modpack makers to re-use these really nicely integrated and textured cups for other drinks in their packs, and not have to have multiple cup items in the pack.

**Comment by KnightMiner** [comment]
In real life, you can drink things besides tea from a tea cup. Tea cup is the style, not the contents. So overall not convinced this is needed.

If modpacks want to reuse tea cups for other drinks, they are free to rename it themselves via a resource pack, or just remember that tea cup is the style so the name does not matter.
