### ISSUE TITLE
Fireweed tea causes crash

### ISSUE THREAD

**Issue by DoctorMage** [elucent/SimplyTea#48]
Drinking fireweed tea causes the game to crash

https://streamable.com/is0dp8

Mods involved
simplytea-1.16.5-2.4.0
cuneiform-1.16.3-1.2.5
terraincognita-1.16.3-1.7.2

Crash Reports
[crash-2022-06-20_03.19.25-server.txt](https://github.com/KnightMiner/SimplyTea/files/8937046/crash-2022-06-20_03.19.25-server.txt)
[crash-2022-06-20_03.17.13-client.txt](https://github.com/KnightMiner/SimplyTea/files/8937048/crash-2022-06-20_03.17.13-client.txt)

Logs
[latest.log](https://github.com/KnightMiner/SimplyTea/files/8937053/latest.log)
[debug.log](https://github.com/KnightMiner/SimplyTea/files/8937054/debug.log)

**Comment by KnightMiner** [comment]
![image](https://user-images.githubusercontent.com/12155288/174524811-1ab56f55-04e4-400f-af11-e9ef58848350.png)

See the mod ID in the tooltip? It is not SimplyTea, so its not my item. There is nothing I can do about this crash. Report to terraincognita.

**Comment by DoctorMage** [comment]
Aplogies have reported it their as well
