### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tempmail344189345** [elucent/SimplyTea#8]
- Teapot refillable from cauldrons
- Placeable teacup and teapot
- More teas?

I love this sweet little mod, please don't abandon it!

**Comment by KnightMiner** [comment]
* I've implemented making teapots fillable from cauldrons in 4f5207b.
* I like the idea of making teacups placable, might be a fun alternative to cake. I'd only want to do it though if I could get it to work with mods such as Nutrition and Tough as Nails.
* More teas is on elucent's original plans, possibly including a floral tea, but not sure what I will do with that.

**Comment by KnightMiner** [comment]
Well, I have just released a version with chai tea, floral tea, and chamomile tea and the feature that makes teapots refillable from cauldrons.

That just leaves placeable teacups, which I have added to my official maybe later list. Will consider it around the same time I look into native TAN support
