### ISSUE TITLE
Feature Request: Whitelist/Blacklist fluids for teapot filling

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [elucent/SimplyTea#9]
I have recently been running into the issue of being unable to fill the teapot with milk in a modded pack due to vanilla cows and liquid milk being unavailable. Only the vanilla bucket is available (Which cannot be crafted with the teapot to add the milk). Being able to fill the teapot with. for example, any of the animania milk types, would be a major benefit as they are capable of being stored in fluid tanks and placed in the world like water and other fluids unlike vanilla milk.

The filled teapot likely does not need a different type for every type of milk or water, simply returning a water filled or milk filled teapot as normal when filled from appropriate whitelisted fluids.

I adore the simplicity of this mod, keep up the good work!

**Comment by KnightMiner** [comment]
Forgot to say, this is in the 1.6 release
